chore: add author page for jgonzalez
cloudnative-pg/cloudnative-pg.github.io pull request #150
Opened 2023-08-14 14:42 UTC by sxd

2023-08-20 16:40 UTC, jsilvela requested changes
bro, please, add a bit of a bio. Otherwise I will add one for you and say you're soooper AWESOME and handsome, and Chuck Norris wishes he could be your friend.

2023-09-02 21:19 UTC, sxd commented
@jsilvela it's that ok with you ? :D

2023-09-03 09:10 UTC, jsilvela approved these changes

2023-09-03 09:11 UTC, jsilvela commented
@sxd beautiful. Made a small modification and IMO, ready to merge.

2023-09-03 17:57 UTC, merged