docs: release announcement for 1.22
cloudnative-pg/cloudnative-pg.github.io pull request #164
Opened 2023-12-14 23:27 UTC by gbartolini

2023-12-18 12:05 UTC, jsilvela requested changes
we have a dupe there I'd like to understand.
Will also keep this one blocked until D-day.

2023-12-18 12:05 UTC, jsilvela commented on content/blog/cloudnative-pg-1-22.0-released/index.md
> +additional tablespace volumes, and also ensure they are used to temporary
```suggestion
additional tablespace volumes, and also ensure they can be used for temporary
```

2023-12-18 12:05 UTC, jsilvela commented on content/blog/cloudnative-pg-1-22.0-released/index.md
> +From 1.22, the `ALTER SYSTEM` command will be disabled by default, to ensure
this and following ... it's a duplicate. @gbartolini are you experimenting different forms, or is this a copy-paste artifact?

2023-12-21 16:48 UTC, jsilvela commented on content/blog/cloudnative-pg-1-22.0-released/index.md
> +From 1.22, the `ALTER SYSTEM` command will be disabled by default, to ensure
Mostly dupe. I added a bit of this one to the "first copy".
Will approve this PR but not merge it or publish it, leaving that to you @gbartolini .
The release documents are now published.

2023-12-21 16:48 UTC, jsilvela approved these changes

2023-12-21 16:53 UTC, mnencia approved these changes

2023-12-21 16:54 UTC, leonardoce approved these changes

2023-12-21 17:44 UTC, jsilvela approved these changes

2023-12-22 03:42 UTC, merged