feat: announce 1.25.0-rc1
cloudnative-pg/cloudnative-pg.github.io pull request #243
Opened 2024-12-07 11:34 UTC by gbartolini

Closes #239

2024-12-07 13:56 UTC, mnencia submitted a review, later dismissed

2024-12-09 09:17 UTC, jsilvela requested changes
I think there's a problem with the link for open issues (suggestion added)

2024-12-09 09:17 UTC, jsilvela commented on content/releases/cloudnative-pg-1-25.0-rc1-released/index.md
> +- View the [open issues for the 1.25 release](https://github.com/cloudnative-pg/cloudnative-pg/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.25.0).
This link doesn't seem to work for me.

```suggestion
- View the [open issues for the 1.25 release](https://github.com/cloudnative-pg/cloudnative-pg/milestone/24).
```

2024-12-09 09:17 UTC, jsilvela commented on content/releases/cloudnative-pg-1-25.0-rc1-released/index.md
> +This release candidate offers a unique opportunity to test new features in your
```suggestion
This release candidate offers a unique opportunity to test the new features in your
```

2024-12-09 10:48 UTC, jsilvela approved these changes

2024-12-09 11:03 UTC, merged